### ISSUE TITLE
Make guzzle optional

### ISSUE THREAD

**Issue by fprochazka** [elasticsearch/elasticsearch-php#124]
Hello,
if I'm correct, there is a `CurlMultiConnection` implementation, that uses just plain curl without any other lib needed. It would be great, if guzzle was moved from `require` to `suggested` and the curl impl could become the default.

Because now if I don't wanna use guzzle, it's still installed no matter what. 

What do you think?

**Comment by polyfractal** [comment]
This is on my short-list for early 2015 priorities.  I'm currently writing tests to see where Guzzle and CurlMultiConnection differ in their output or API.  If the differences are simple enough, I can do the switch without a major version change.

If the APIs are too dis-similar, and there is no way to fix it in a bwc manner, I'll have to bump the change to 2.0

**Comment by polyfractal** [comment]
ES-PHP 2.0 now uses `RingPHP` (Guzzle5's http transport core) instead of Guzzle directly, so the only requirement is RingPHP itself.  You can use the handlers that come with it, or implement your own.  This drastically reduces the dependency footprint of v2.0

Seeing as Guzzle3 is *extremely* old and deprecated at this point, I don't want to invest much effort into making it optional in v1.x ... if you want a smaller footprint, just use v2.x :)

**Comment by Erutan409** [comment]
I'm confused...  If it's now no longer a requirement, why was it still downloaded as a dependency when I installed the library no longer than 3 weeks ago?

**Comment by polyfractal** [comment]
What version of ES-PHP did you install?  2.0 is still in beta (currently `v2.0.0-beta3`), so unless you explicitly told composer to allow for beta-stability, you're still on ES-1.0.  Which is still using Guzzle 3 :)

**Comment by Erutan409** [comment]
I retract my confusion and replace it with better understanding.  I was losing track of which dependencies I already had downloaded in my vendor folder and now realize what you outlined.

Thank you, sir!

**Comment by polyfractal** [comment]
No worries, happy to help :)

You'd be surprised (or disappointed heh) to see how often I switch branches and forget to update dependencies, and subsequently scratch my head at strange errors :)
