### ISSUE TITLE
Cannot Use a Current Elasticsearch PHP Version with Silex 1.X

### ISSUE THREAD

**Issue by chrisguitarguy** [elasticsearch/elasticsearch-php#167]
Silex's current latest stable version is 1.2.2 at the the time of writing. Silex 1.X uses the old Pimple 1.0 library. That means anyone using Elasticsearch with Silex is stuck on v1.1 of this library, which is missing some fixes (I ran into #97, specifically).

Looks like the switch to Pimple 2.0+ came in e1cc94e5e8275d59e448f66319553377edef84ad (v1.2 of this library).

Not sure if anything can be done about this, but I thought it was worth getting out there for anyone else with the same issue.

**Comment by polyfractal** [comment]
Yeah, unfortunately [not much that can be done](https://github.com/elasticsearch/elasticsearch-php/issues/160#issuecomment-65268768) about it at the moment.  

I just opened #172 about potentially dropping Pimple for an "in-house" replacement, so we don't run into these kinds of problems in the future.

**Comment by polyfractal** [comment]
As an update, ES-PHP v2.0 doesn't use Pimple anymore, so you should be safe to combine the two again :)
