### ISSUE TITLE
Investigate dropping Pimple

### ISSUE THREAD

**Issue by polyfractal** [elasticsearch/elasticsearch-php#172]
The client library uses Pimple for dependency injection and shared services.  Because Pimple is simple and convenient, many other projects also use it.  Due to the recent high turnover in major, backwards-breaking versions, dependency conflicts with Pimple have become a relatively serious problem preventing integration.

This may be a transient event due to the high turnover in major versions (due to class alias issues), but it has caused enough commotion that I would like to investigate if Pimple can be removed, using an "in house" system instead.  

The client already uses the factory pattern in several locations.  It might be possible to simply extend the factory interfaces and standardize the injection, then provide a simple Pimple-replacement.

This may or may not be possible.  Needs active investigation

### Pros
- One less dependency
- Pimple is used widely, so it is a common dependency to conflict with. Integral to functionality, so cannot be moved to suggest
- Being used relatively simplistically, shouldn't be terrible to replace

### Cons
- More code to maintain
- Fewer eyeballs on a potentially performance bottleneck
- Lose ability to use the Pimple C extension

**Comment by fprochazka** [comment]
I think the main problem is the wrong usage of the pimple lib. Instead of beein the integration point, it's integrated deeply in the lib and the lib just doesn't work without it.

**Comment by fprochazka** [comment]
I think the main problem is the wrong usage of the pimple lib. Instead of beein the integration point, it's integrated deeply in the lib and the lib just doesn't work without it. You're using it as a service locator, not DI Container.

Make the lib unaware of the fact that pimple is used and then create some simple factory class, that will pick everything and inject it everywhere it's needed, returning configured client.

**Comment by polyfractal** [comment]
Yeah, I agree with your assessment.  I've always been dissatisfied with how I'm using Pimple, and the horribly clunky way to "plug in" third-party implementation of the various components.  Ditto for requiring both `psr/log` *and* `monolog/monlog`, which rather defeats the point of relying on an interface like `psr/log`.

Will spin up a branch to play around with alternatives.

**Comment by polyfractal** [comment]
Pimple was dropped in favor of a simpler Builder pattern.  The user now has an option to build it manually, or use something like Pimple themselves to manage the building of the client.
