### ISSUE TITLE
Drop support for PHP 5.3?

### ISSUE THREAD

**Issue by polyfractal** [elasticsearch/elasticsearch-php#173]
PHP 5.3 was released six years ago, in [June of 2009](http://php.net/ChangeLog-5.php#5.3.0).  It was [EOL'd four months ago](http://php.net/eol.php), in August 2014.

Many popular PHP libraries, such as [Guzzle](https://github.com/guzzle/guzzle/), [Drupal 8](https://www.drupal.org/requirements), [Laravel](http://laravel.com/docs/4.2/installation#server-requirements), and [Magento](http://magento.com/resources/system-requirements), have already migrated to PHP 5.4

The change would introduce the usual bevy of bug fixes, performance enhancements, security fixes and new features (array shorthand and traits are most likely to be used by this project).  But the biggest benefit would be fitting into the 5.4. ecosystem and being able to leverage projects like Guzzle4.

Thoughts?  How many people are still stuck on PHP 5.3 and unable to upgrade?

**Comment by LordGaav** [comment]
Not a problem for me personally, but do keep in mind that Ubuntu 12.04 ships with PHP 5.3 and is supported until April 2017.

**Comment by treyhyde** [comment]
5.3 is EOL, kill it.  Ubuntu LTS is 14.04 now.

**Comment by mguillermin** [comment]
:+1: for dropping PHP 5.3 support

**Comment by damienalexandre** [comment]
:+1: for dropping PHP 5.3 support.

Projects starting in 2015 should not rely on such an old PHP version, and I do not see any issue for existing projects, they can stick to a compatible version of the library.

**Comment by penfold45** [comment]
I vote to drop it.

**Comment by ryantology** [comment]
TL;DR Drop 5.3

I am sure you are going to end up with a lot of 'me too' on here. We have a handful of legacy applications that use elasticsearch. We took the time (not that much time really) this year to upgrade everything to 5.4. I am sure that there will be vulnerabilities found in 5.3.29 soon and I assume php will not be publishing security patches? This would make dropping support a natural progression.

**Comment by fprochazka** [comment]
Kill it with fire :)

**Comment by jprante** [comment]
+1k please drop unsupported versions asap

**Comment by xreal** [comment]
+1 for dropping 5.3, for me PHP 5.5 would be fine!
5.4 EOL is in September 2015?

**Comment by krzaczek** [comment]
Drop it ... 5.3 is officialy "End of Life" so it's time to upgrade .... You can always force version v1.3 in composer if You NEED to use php 5.3

**Comment by versgui** [comment]
Go ahead, :+1: for dropping PHP 5.3 support.

**Comment by nathankurtyka** [comment]
PHP 5.3 is (by far) the most popular version of PHP out there: http://w3techs.com/technologies/details/pl-php/5/all

Although cleaner and faster code is a good thing, I think that maintaining compatibility with the most common PHP version will do a lot more to spur adoption.

**Comment by fprochazka** [comment]
Everyone who thinks 5.3 should be maintained... read this:

http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html
http://blog.ircmaxell.com/2014/12/being-responsible-developer.html

**Comment by xboston** [comment]
+1

**Comment by eddiejaoude** [comment]
:+1:

**Comment by egulias** [comment]
:+1:

**Comment by cystbear** [comment]
:+1:

**Comment by thewunder** [comment]
For 2.0 I think breaking 5.3 is fine

**Comment by guenterh** [comment]
We are running our service (www.swissbib.ch) on RedHat 6.4 where version 5.3 is the standard. We deployed a PHP 5.4 version which wasn't a problem at all. From my point of view there no reason to support the outdated version.

**Comment by polyfractal** [comment]
Awesome!  I honestly wasn't expecting such a unanimous and encouraging response.

Short of a cataclysmic reason for staying on 5.3, the ES-PHP 2.0 will target 5.4. ![emot-toot](https://cloud.githubusercontent.com/assets/1224228/5614106/6b50d272-94bb-11e4-916f-5ea04679e378.gif)

**Comment by polyfractal** [comment]
PHP 5.3 was dropped for ES-PHP 2.0. 

There was much rejoicing!
