### ISSUE TITLE
Bug in Scroll.php line 81 or outdated documentation?

### ISSUE THREAD

**Issue by csabo** [elasticsearch/elasticsearch-php#182]
Hello, 
 My apologies if this has been opened previously I did not find it.

we are having issues with Scroll. I've pasted the output below. If we manually take that generated URL and use curl on it, we see the data results. ANY help would be amazing!

[Elasticsearch\Common\Exceptions\Missing404Exception]
  {"_scroll_id":"c2NhbjswOzE7dG90YWxfaGl0czo2MjIxOw==","took":11,"timed_out":false,"_shards":{"total":5,"successful":0,"failed":5,"failures":
  [{"status":404,"reason":"SearchContextMissingException[No search context found for id [216741]]"},{"status":404,"reason":"SearchContextMiss
  ingException[No search context found for id [216743]]"},{"status":404,"reason":"SearchContextMissingException[No search context found for i
  d [216745]]"},{"status":404,"reason":"SearchContextMissingException[No search context found for id [216742]]"},{"status":404,"reason":"Sear
  chContextMissingException[No search context found for id [216744]]"}]},"hits":{"total":6221,"max_score":0.0,"hits":[]}}

  [Guzzle\Http\Exception\ClientErrorResponseException]
  Client error response
  [status code] 404
  [reason phrase] Not Found
  [url] http://10.0.1.223:9200/_search/scroll/c2Nhbjs1OzIxNjc0MTpZYVNkLXBwd1FGYTY5aWZaZkt5TlVROzIxNjc0MzpZYVNkLXBwd1FGYTY5aWZaZkt5TlVROzIxNjc
  0NTpZYVNkLXBwd1FGYTY5aWZaZkt5TlVROzIxNjc0MjpZYVNkLXBwd1FGYTY5aWZaZkt5TlVROzIxNjc0NDpZYVNkLXBwd1FGYTY5aWZaZkt5TlVROzE7dG90YWxfaGl0czo2MjIxOw
  ==?scroll=1m

**Comment by csabo** [comment]
Looking at line 81 in Scroll.php it appears that there is either a bug, or outdated documentation

https://github.com/elasticsearch/elasticsearch-php/blob/8ea360d6bea7e554847a40d681fd52e436d6104d/src/Elasticsearch/Endpoints/Scroll.php

**Comment by polyfractal** [comment]
Sorry for the delay, been traveling and away from a computer.

I suspect your scroll window is timing out, which can cause that exception.

- How long of a scroll window are you specifying? 
- Are you setting the timeout on each request?   The timeout is only for the duration until the next call, not the entire scan/scroll operation
- And are you sending back the new scroll_id that ES provides each time (it can change sometimes, so you always have to send the most recent scroll_id)

The URL format (`/_search/scroll/{scroll_id}`) should work based on the [Elasticsearch source code](https://github.com/elasticsearch/elasticsearch/blob/1.4/src/main/java/org/elasticsearch/rest/action/search/RestSearchScrollAction.java#L47) for the scroll parsing.

**Comment by csabo** [comment]
Thank you so much for the reply. It turns out we are just idiots. It wasn't a timeout. in copying and pasting  the example code something was missed, and was subsequently overlooked. 

My apologies for wasting your time.

-Chris

**Comment by polyfractal** [comment]
Ah, cool.  Happy you figured it out!  And no worries about the ticket, user support is a good way to fill time in between tests and builds and the like :)
