### ISSUE TITLE
About CRUD operations

### ISSUE THREAD

**Issue by marciomansur** [elasticsearch/elasticsearch-php#183]
Hello.

Do you have a simple example of how to update a document data using the function update, ate the "Client.php" file? I need to set a new field on my document e update others. Thank you.

**Comment by polyfractal** [comment]
There is an example in the repo's Readme:  https://github.com/elasticsearch/elasticsearch-php#update-a-document

Although I just noticed there isn't an example in the docs...I'll add it shortly.
