### ISSUE TITLE
Exclude Types for Search

### ISSUE THREAD

**Issue by itonics-tbeauvais** [elasticsearch/elasticsearch-php#187]
There are some types that I want to exclude depending on a programmatic criteria (security, filters, so on) but can't seem to find anything on how to do that.  

Any insight would be greatly appreciated. :) 

        $params = array();
        $params['index'] = "my_index";
        $params['body']['query']['filtered']['filter']['not']['type'] = 'my_type';

        $results = $this->client->search($params);

**Comment by mguillermin** [comment]
The `type` filter expects a `value` property containing the type name. (see http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-type-filter.html)

Taking your example, this should look like this : 
```
    $params['body']['query']['filtered']['filter']['not']['type']['value'] = 'my_type';
```

**Comment by itonics-tbeauvais** [comment]
Thanks!  Works beautifully. :)
