### ISSUE TITLE
How to use term-aggregations in elastic search for OR condition

### ISSUE THREAD

**Issue by zekiunal** [elasticsearch/elasticsearch-php#189]
i have the following data:

person1: { city: a, education: x}
person2: { city: a, education: y}
person3: { city: a, education: x}
person4: { city: b, education: y}
person5: { city: c, education: x}

All form items dynamic and come from elasticsearch aggreations.

----------------------------------------------------------------

Cases
---------------------

#### Non-Selected

Request : 

```json
{
  "aggregations": {
    "cities": {"terms": {"field": "city"}},
    "educations": {"terms": {"field": "education"}}
  },
  "query": {
    "filtered": {
      "query": {"match_all": []}
    }
  }
}
```
Response : 

city:
  () "a": 3
  () "b": 1
  () "c": 1
education:
  () "x": 3
  () "y": 2

--------------------------------------------------------------------------

#### "a" selected

```json
{
  "aggregations": {
    "cities": {"terms": {"field": "city"}},
    "educations": {"terms": {"field": "education"}}
  },
  "query": {
    "filtered": {
      "query": {"match_all": []},
      "filter": {
        "bool": {
          "must": [
            {"bool": {"should": [{"term": {"city": "a"}}]}}
          ]
        }
      }
    }
  }
}

```

Form : 

city:
  (x) "a": 3
  ()   "b": 0 -> this reason its not come from engine
  ()   "c": 0 -> this reason its not come from engine
education:
  () "x": 2
  () "y": 1

Now : 

I want to get "or" condition for this aggregation.  Like this : 

city:
  (x) "a": 3
  ()   "b": 1 -> I wanna see this options too for show posibilities
  ()   "c": 1
education:
  () "x": 2
  () "y": 1

how can i do this?

**Comment by polyfractal** [comment]
You will need to use a `post_filter`, rather than a filtered query.  Aggregations use the same "data scope" as the query, meaning that a filtered_query will filter both the query and the aggregation results.  A `post_filter` filters after the query executes, so the agg results are untouched.

You can read more about it here:  http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_filtering_queries_and_aggregations.html
