### ISSUE TITLE
How do i sort on geo location as well as other fields

### ISSUE THREAD

**Issue by imhimanshu** [elasticsearch/elasticsearch-php#191]
Following is my code

```php
$arrParams['sort'] = array(
  array(
    "_geo_distance" => array(
      "geo_location" => array(
        "lat" => 18.9295932,
        "lon" => 72.83272960000001
      ) ,
      "order" => "asc",
      "unit" => "km"
    )
  ) ,
  array(
    "likes_count" => array(
      'order' => 'desc'
    )
  ) ,
  array(
    "reviews.created_time" => array(
      'order' => 'desc'
    )
  )
);
$query['bool']['must'][]['term']['status'] = '1';
$query['bool']['must'][]['term']['category.category_id'] = 103;
$arrParams['body']['query'] = $query;
$client = new ElasticsearchClient();
$arrResult = $client->search($arrParams);
```

When i am trying to use geo sorting along with my other parameters it is not working, if i will use following normal sorting then it is working perfectly. 

$arrParams['sort'] = array ("likes_count:desc,reviews.created_time:desc");

I did not find help anywhere, can you guys please help me how do i solve this issue.

**Comment by polyfractal** [comment]
Hmm, the syntax looks correct.  Can you paste the search response that is not being properly sorted so I can take a look at the ordering and document layout?

**Comment by imhimanshu** [comment]
Thanks for quick reply, in search response i am not getting any error, i get proper result set but not in desired order. I solved this problem by using Query DSL by following code.
$arrParams['sort'] = array (
array ("_geo_distance" =>
array ("geo_location" => array ("lat"=> 18.9295932, "lon"=> 72.83272960000001),
"order"=>"asc", "unit"=>"km")
),
array ("likes_count" => array ('order' => 'desc')),
array ("reviews.created_time" => array ('order' => 'desc'))
);
$query['bool']['must'][]['term']['status'] = '1';
$query['bool']['must'][]['term']['category.category_id'] = 103;

$arrParams['query'] = $query;

            $arrFinalQuery['index'] = 'spnew';
            $arrFinalQuery['type']  = 'sprovider_new';
            $arrFinalQuery['body'] = json_encode($arrParams);

$client = new Elasticsearch\Client();
$arrResult = $client->search($arrFinalQuery);

instead of passing array now i am passing JSON in body and i am getting result in proper order:
Array
(
    [index] => spnew
    [type] => sprovider_new
    [body] => {"from":0,"size":15,"sort":[{"_geo_distance":{"geo_location":{"lat":18.9295932,"lon":72.8327296},"order":"asc","unit":"km"}},{"likes_count":{"order":"desc"}},{"reviews.created_time":{"order":"desc"}}],"query":{"bool":{"must":[{"term":{"status":"1"}},{"term":{"category.category_id":"103"}},{"term":{"parent_service_id":"0"}},{"term":{"city_id":"1"}}]}}}
)

**Comment by polyfractal** [comment]
Ah, I missed a problem in your original syntax, which you fixed in your second version.  That's why it works...not the JSON encoding.

Complex sort parameters are specified as a part of the body, not as part of the request params.  So your original example should be:

```php
$arrParams['body']['sort'] = array(  // <-- Notice we add the sort to ['body'] now
  array(
    "_geo_distance" => array(
      "geo_location" => array(
        "lat" => 18.9295932,
        "lon" => 72.83272960000001
      ) ,
      "order" => "asc",
      "unit" => "km"
    )
  ) ,
  array(
    "likes_count" => array(
      'order' => 'desc'
    )
  ) ,
  array(
    "reviews.created_time" => array(
      'order' => 'desc'
    )
  )
);
$query['bool']['must'][]['term']['status'] = '1';
$query['bool']['must'][]['term']['category.category_id'] = 103;
$arrParams['body']['query'] = $query;
$client = new ElasticsearchClient();
$arrResult = $client->search($arrParams);
```


Your second example does the same thing basically:

```php
$arrParams['sort'] = array( ... );
$arrParams['query'] = $query;

$arrFinalQuery['body'] = json_encode($arrParams);  // <-- `sort` get's put inside of `body` now
```

Also, note, your second example is specifying an index and type, so the search results will be a bit different from the first example.

As a final note, consider scoring on distance rather than sorting on distance.  It tends to give better results.  More details here:  http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/sorting-by-distance.html#scoring-by-distance
