### ISSUE TITLE
A confuse with how to use createRepository in SnapshotNamespace

### ISSUE THREAD

**Issue by williamzhao** [elasticsearch/elasticsearch-php#197]
Hi there!
 I knew that ES can create snapshot and restore indices in the terminal ,as this:

```php
curl -XPUT 'http://localhost:6800/_snapshot/respository' -d '{
    "type": "fs",
    "settings": {
        "location": "/mount/backups/udoo",
        "compress": true
    }
}'
```

But I just can't guess how to pass parameters to the createRepository in SnapshotNamespace, It has
two parameters:repository and body.

When I got this : 
$indexParams = array();
$indexParams['repository']    = 'repository';
$indexParams['body']['index']  = 'udo_index';
$indexParams['body']['type']  = 'udo_item';
return ES_IndexService::instance()->snapshot()->createRepository($indexParams);

It says: repository missing ,after that,I manually create a repository,it got another error

thanks for your answer!

**Comment by polyfractal** [comment]
Not quite sure I follow... you need to recreate the JSON syntax in the PHP request.  Like this:

```php
$indexParams = [
    'repository' => 'repository',
    'body' => [
        'type' => 'fs',
        'settings' => [
            'location' => '/mount/backups/udoo',
            'compress' => true
        ]
    ]
];

return ES_IndexService::instance()->snapshot()->createRepository($indexParams);
```

Or are you trying to do something else (e.g. like create a snapshot, not a repository) ?

**Comment by williamzhao** [comment]
It works ! thanks a lot !
